### ISSUE TITLE
What is exactly the authorization code?

### ISSUE THREAD

**Issue by glowiak** [HyCraftHD/Minecraft-Authenticator#4]
I dropped in my msaid, but this error popped out:

net.hycrafthd.minecraft_authenticator.microsoft.MicrosoftAuthenticationException: Cannot get oAuth token because: OAuthError [error=invalid_grant, errorDescription=The provided value for the 'code' parameter is not valid., correlationId=884cd3ea-a5cb-413f-b288-b9b241572197]
        at net.hycrafthd.minecraft_authenticator.util.AuthenticationUtil.createMicrosoftAuthenticationFile(AuthenticationUtil.java:61)
        at net.hycrafthd.minecraft_authenticator.login.Authenticator.lambda$ofMicrosoft$1(Authenticator.java:126)
        at net.hycrafthd.minecraft_authenticator.login.Authenticator.<init>(Authenticator.java:259)
        at net.hycrafthd.minecraft_authenticator.login.Authenticator$Builder.run(Authenticator.java:242)
        at net.minecraft.LoginForm$1.actionPerformed(LoginForm.java:76)
        at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
        at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
        at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
        at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
        at java.awt.Component.processMouseEvent(Component.java:6539)
        at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
        at java.awt.Component.processEvent(Component.java:6304)
        at java.awt.Container.processEvent(Container.java:2239)
        at java.awt.Component.dispatchEventImpl(Component.java:4889)
        at java.awt.Container.dispatchEventImpl(Container.java:2297)
        at java.awt.Component.dispatchEvent(Component.java:4711)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
        at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
        at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
        at java.awt.Container.dispatchEventImpl(Container.java:2283)
        at java.awt.Component.dispatchEvent(Component.java:4711)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
        at java.awt.EventQueue$4.run(EventQueue.java:733)
        at java.awt.EventQueue$4.run(EventQueue.java:731)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by HyCraftHD** [comment]
Here is some description about this: https://github.com/HyCraftHD/Minecraft-Authenticator/blob/36260ed9e8f4f45ccf47064df68c32401e5f4cf5/src/main/java/net/hycrafthd/minecraft_authenticator/login/Authenticator.java#L33-L40

Basically it's the value (????) of the code parameter in this url: ``https://login.live.com/oauth20_desktop.srf?code=?????``

**Comment by glowiak** [comment]
Great but how do I get it. I mean is there a way to like open a web browser in java and get the result?

**Comment by glowiak** [comment]
@HyCraftHD Okay I have implemented opening this login page (with Runtime.getRuntime().exec(), because my system does not support Desktop.browse()) , but how do I get the result?

**Comment by HyCraftHD** [comment]
You can only get it with a custom azure application, because the vanilla azure id does not allow a redirect url to localhost.

There are two options:
1. Open the webpage in your java gui application (e.g. javafx webview)
2. Create a custom azure application and set the redirect url to localhost. (You may have a look here for an example: https://github.com/HyCraftHD/Simple-Minecraft-Authenticator/blob/3ef36130f815da7703a9de02d985089f7504d75c/src/main/java/net/hycrafthd/simple_minecraft_authenticator/method/WebAuthentication.java#L50)

**Comment by glowiak** [comment]
thank you

**Comment by glowiak** [comment]
@HyCraftHD Wait, is there a way to just get 0 or 1 if the login was successful or not instead of all this complicated code stuff?

**Comment by glowiak** [comment]
@HyCraftHD 
This is my code:

```
                      String code = "";
                      StringSelection ab = new StringSelection(Authenticator.microsoftLogin().toString());
                      Toolkit.getDefaultToolkit().getSystemClipboard().setContents(ab, ab);
                      JOptionPane.showMessageDialog(null, "Open the url in clipboard and give result");
                      code = JOptionPane.showInputDialog(null, "Enter the output URL");
                      String c1 = code.substring("https://login.live.com/oauth20_desktop.srf?code=".length());
                      int ac = c1.indexOf("&");
                      if (ac > 0)
                      {
                          code = c1.substring(0, ac);
                      }
                      System.out.println(code);
                      if (code != null && code.length() > 0)
                      {
                        try {
                              Authenticator auth = Authenticator.ofMicrosoft(code).customAzureApplication(MSAID, "localhost").shouldAuthenticate().run();
                              AuthenticationFile af = auth.getResultFile();
                              Optional<User> user = auth.getUser();
                              userName.setText(user.get().getName());
                        } catch (Exception ee)
                        {
                              ee.printStackTrace();
                        }
                     }
```

it does not work

**Comment by glowiak** [comment]
and the error I get is

```
M.R3_BL2.5f2c613fdsgdfgdfgdfgdfgdgfa
net.hycrafthd.minecraft_authenticator.microsoft.MicrosoftAuthenticationException: Cannot get oAuth token because: OAuthError [error=invalid_grant, errorDescription=The provided value for the 'code' parameter is not valid., correlationId=0377921b-b303-435c-b0fc-72bbb5f0ba66]
        at net.hycrafthd.minecraft_authenticator.util.AuthenticationUtil.createMicrosoftAuthenticationFile(AuthenticationUtil.java:61)
        at net.hycrafthd.minecraft_authenticator.login.Authenticator.lambda$ofMicrosoft$1(Authenticator.java:126)
        at net.hycrafthd.minecraft_authenticator.login.Authenticator.<init>(Authenticator.java:259)
        at net.hycrafthd.minecraft_authenticator.login.Authenticator$Builder.run(Authenticator.java:242)
        at net.minecraft.LoginForm$1.actionPerformed(LoginForm.java:88)
        at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
        at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
        at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
        at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
        at java.awt.Component.processMouseEvent(Component.java:6539)
        at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
        at java.awt.Component.processEvent(Component.java:6304)
        at java.awt.Container.processEvent(Container.java:2239)
        at java.awt.Component.dispatchEventImpl(Component.java:4889)
        at java.awt.Container.dispatchEventImpl(Container.java:2297)
        at java.awt.Component.dispatchEvent(Component.java:4711)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
        at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
        at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
        at java.awt.Container.dispatchEventImpl(Container.java:2283)
        at java.awt.Component.dispatchEvent(Component.java:4711)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
        at java.awt.EventQueue$4.run(EventQueue.java:733)
        at java.awt.EventQueue$4.run(EventQueue.java:731)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)


```

**Comment by HyCraftHD** [comment]
What does the passed in authorization code looks like?
Please censor stuff in the middle / and remove number codes.

**Comment by glowiak** [comment]
M.R3_BL2.edb0f063-c145-****-****-c8bd6c04fcf2

**Comment by glowiak** [comment]
first line in the log was the exact code
also why does it need to be censored?

**Comment by glowiak** [comment]
@HyCraftHD

**Comment by glowiak** [comment]
@HyCraftHD

**Comment by HyCraftHD** [comment]
Yes the code seems right. Do you use the same client_id for the login window and the rest of the application?
What is the URL for the page where you login?

This code gives you access to the minecraft azure application. You can then login into minecraft. It should never be shared publicly.

**Comment by glowiak** [comment]
@HyCraftHD 

I just call my launcher to open firefox and copy the code to clipboard.

Also, why can't I share it?
